#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelloWorld
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DboTicariOtomasyon")]
	public partial class TicariBaglantiDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTBL_BANKALAR(TBL_BANKALAR instance);
    partial void UpdateTBL_BANKALAR(TBL_BANKALAR instance);
    partial void DeleteTBL_BANKALAR(TBL_BANKALAR instance);
    partial void InsertTBL_FATURABILGI(TBL_FATURABILGI instance);
    partial void UpdateTBL_FATURABILGI(TBL_FATURABILGI instance);
    partial void DeleteTBL_FATURABILGI(TBL_FATURABILGI instance);
    partial void InsertTBL_FATURADETAY(TBL_FATURADETAY instance);
    partial void UpdateTBL_FATURADETAY(TBL_FATURADETAY instance);
    partial void DeleteTBL_FATURADETAY(TBL_FATURADETAY instance);
    partial void InsertTBL_ILCELER(TBL_ILCELER instance);
    partial void UpdateTBL_ILCELER(TBL_ILCELER instance);
    partial void DeleteTBL_ILCELER(TBL_ILCELER instance);
    partial void InsertTBL_MUSTERILER(TBL_MUSTERILER instance);
    partial void UpdateTBL_MUSTERILER(TBL_MUSTERILER instance);
    partial void DeleteTBL_MUSTERILER(TBL_MUSTERILER instance);
    partial void InsertTBL_NOTLAR(TBL_NOTLAR instance);
    partial void UpdateTBL_NOTLAR(TBL_NOTLAR instance);
    partial void DeleteTBL_NOTLAR(TBL_NOTLAR instance);
    partial void InsertTBL_STOKLAR(TBL_STOKLAR instance);
    partial void UpdateTBL_STOKLAR(TBL_STOKLAR instance);
    partial void DeleteTBL_STOKLAR(TBL_STOKLAR instance);
    partial void InsertTBL_URUNLER(TBL_URUNLER instance);
    partial void UpdateTBL_URUNLER(TBL_URUNLER instance);
    partial void DeleteTBL_URUNLER(TBL_URUNLER instance);
    partial void InsertTBL_KULLANICILAR(TBL_KULLANICILAR instance);
    partial void UpdateTBL_KULLANICILAR(TBL_KULLANICILAR instance);
    partial void DeleteTBL_KULLANICILAR(TBL_KULLANICILAR instance);
    partial void InsertTBL_ILLER(TBL_ILLER instance);
    partial void UpdateTBL_ILLER(TBL_ILLER instance);
    partial void DeleteTBL_ILLER(TBL_ILLER instance);
    partial void InsertTBL_FIRMALAR(TBL_FIRMALAR instance);
    partial void UpdateTBL_FIRMALAR(TBL_FIRMALAR instance);
    partial void DeleteTBL_FIRMALAR(TBL_FIRMALAR instance);
    partial void InsertTBL_OZELKODLAR(TBL_OZELKODLAR instance);
    partial void UpdateTBL_OZELKODLAR(TBL_OZELKODLAR instance);
    partial void DeleteTBL_OZELKODLAR(TBL_OZELKODLAR instance);
    partial void InsertTBL_PERSONELLER(TBL_PERSONELLER instance);
    partial void UpdateTBL_PERSONELLER(TBL_PERSONELLER instance);
    partial void DeleteTBL_PERSONELLER(TBL_PERSONELLER instance);
    partial void InsertTBL_GIDERLER(TBL_GIDERLER instance);
    partial void UpdateTBL_GIDERLER(TBL_GIDERLER instance);
    partial void DeleteTBL_GIDERLER(TBL_GIDERLER instance);
    #endregion
		
		public TicariBaglantiDataContext() : 
				base(global::HelloWorld.Properties.Settings.Default.DboTicariOtomasyonConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TicariBaglantiDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TicariBaglantiDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TicariBaglantiDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TicariBaglantiDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TBL_BANKALAR> TBL_BANKALARs
		{
			get
			{
				return this.GetTable<TBL_BANKALAR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_FATURABILGI> TBL_FATURABILGIs
		{
			get
			{
				return this.GetTable<TBL_FATURABILGI>();
			}
		}
		
		public System.Data.Linq.Table<TBL_FATURADETAY> TBL_FATURADETAYs
		{
			get
			{
				return this.GetTable<TBL_FATURADETAY>();
			}
		}
		
		public System.Data.Linq.Table<TBL_ILCELER> TBL_ILCELERs
		{
			get
			{
				return this.GetTable<TBL_ILCELER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_MUSTERILER> TBL_MUSTERILERs
		{
			get
			{
				return this.GetTable<TBL_MUSTERILER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_NOTLAR> TBL_NOTLARs
		{
			get
			{
				return this.GetTable<TBL_NOTLAR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_STOKLAR> TBL_STOKLARs
		{
			get
			{
				return this.GetTable<TBL_STOKLAR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_URUNLER> TBL_URUNLERs
		{
			get
			{
				return this.GetTable<TBL_URUNLER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_KULLANICILAR> TBL_KULLANICILARs
		{
			get
			{
				return this.GetTable<TBL_KULLANICILAR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_ILLER> TBL_ILLERs
		{
			get
			{
				return this.GetTable<TBL_ILLER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_FIRMALAR> TBL_FIRMALARs
		{
			get
			{
				return this.GetTable<TBL_FIRMALAR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_OZELKODLAR> TBL_OZELKODLARs
		{
			get
			{
				return this.GetTable<TBL_OZELKODLAR>();
			}
		}
		
		public System.Data.Linq.Table<TBL_PERSONELLER> TBL_PERSONELLERs
		{
			get
			{
				return this.GetTable<TBL_PERSONELLER>();
			}
		}
		
		public System.Data.Linq.Table<TBL_GIDERLER> TBL_GIDERLERs
		{
			get
			{
				return this.GetTable<TBL_GIDERLER>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_BANKALAR")]
	public partial class TBL_BANKALAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _ID;
		
		private string _BANKAADI;
		
		private string _SUBE;
		
		private string _IBAN;
		
		private string _HESAPNO;
		
		private string _YETKILI;
		
		private System.Nullable<System.DateTime> _TARIH;
		
		private string _HESAPTURU;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(byte value);
    partial void OnIDChanged();
    partial void OnBANKAADIChanging(string value);
    partial void OnBANKAADIChanged();
    partial void OnSUBEChanging(string value);
    partial void OnSUBEChanged();
    partial void OnIBANChanging(string value);
    partial void OnIBANChanged();
    partial void OnHESAPNOChanging(string value);
    partial void OnHESAPNOChanged();
    partial void OnYETKILIChanging(string value);
    partial void OnYETKILIChanged();
    partial void OnTARIHChanging(System.Nullable<System.DateTime> value);
    partial void OnTARIHChanged();
    partial void OnHESAPTURUChanging(string value);
    partial void OnHESAPTURUChanged();
    #endregion
		
		public TBL_BANKALAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="TinyInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public byte ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BANKAADI", DbType="VarChar(30)")]
		public string BANKAADI
		{
			get
			{
				return this._BANKAADI;
			}
			set
			{
				if ((this._BANKAADI != value))
				{
					this.OnBANKAADIChanging(value);
					this.SendPropertyChanging();
					this._BANKAADI = value;
					this.SendPropertyChanged("BANKAADI");
					this.OnBANKAADIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBE", DbType="VarChar(30)")]
		public string SUBE
		{
			get
			{
				return this._SUBE;
			}
			set
			{
				if ((this._SUBE != value))
				{
					this.OnSUBEChanging(value);
					this.SendPropertyChanging();
					this._SUBE = value;
					this.SendPropertyChanged("SUBE");
					this.OnSUBEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IBAN", DbType="VarChar(30)")]
		public string IBAN
		{
			get
			{
				return this._IBAN;
			}
			set
			{
				if ((this._IBAN != value))
				{
					this.OnIBANChanging(value);
					this.SendPropertyChanging();
					this._IBAN = value;
					this.SendPropertyChanged("IBAN");
					this.OnIBANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESAPNO", DbType="VarChar(20)")]
		public string HESAPNO
		{
			get
			{
				return this._HESAPNO;
			}
			set
			{
				if ((this._HESAPNO != value))
				{
					this.OnHESAPNOChanging(value);
					this.SendPropertyChanging();
					this._HESAPNO = value;
					this.SendPropertyChanged("HESAPNO");
					this.OnHESAPNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKILI", DbType="VarChar(30)")]
		public string YETKILI
		{
			get
			{
				return this._YETKILI;
			}
			set
			{
				if ((this._YETKILI != value))
				{
					this.OnYETKILIChanging(value);
					this.SendPropertyChanging();
					this._YETKILI = value;
					this.SendPropertyChanged("YETKILI");
					this.OnYETKILIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIH", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> TARIH
		{
			get
			{
				return this._TARIH;
			}
			set
			{
				if ((this._TARIH != value))
				{
					this.OnTARIHChanging(value);
					this.SendPropertyChanging();
					this._TARIH = value;
					this.SendPropertyChanged("TARIH");
					this.OnTARIHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HESAPTURU", DbType="VarChar(20)")]
		public string HESAPTURU
		{
			get
			{
				return this._HESAPTURU;
			}
			set
			{
				if ((this._HESAPTURU != value))
				{
					this.OnHESAPTURUChanging(value);
					this.SendPropertyChanging();
					this._HESAPTURU = value;
					this.SendPropertyChanged("HESAPTURU");
					this.OnHESAPTURUChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_FATURABILGI")]
	public partial class TBL_FATURABILGI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<char> _SERI;
		
		private string _SIRANO;
		
		private System.Nullable<System.DateTime> _TARIH;
		
		private System.Nullable<System.TimeSpan> _SAAT;
		
		private string _VERGIDAIRE;
		
		private string _ALICI;
		
		private string _TESLIMEDEN;
		
		private string _TESLIMALAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSERIChanging(System.Nullable<char> value);
    partial void OnSERIChanged();
    partial void OnSIRANOChanging(string value);
    partial void OnSIRANOChanged();
    partial void OnTARIHChanging(System.Nullable<System.DateTime> value);
    partial void OnTARIHChanged();
    partial void OnSAATChanging(System.Nullable<System.TimeSpan> value);
    partial void OnSAATChanged();
    partial void OnVERGIDAIREChanging(string value);
    partial void OnVERGIDAIREChanged();
    partial void OnALICIChanging(string value);
    partial void OnALICIChanged();
    partial void OnTESLIMEDENChanging(string value);
    partial void OnTESLIMEDENChanged();
    partial void OnTESLIMALANChanging(string value);
    partial void OnTESLIMALANChanged();
    #endregion
		
		public TBL_FATURABILGI()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SERI", DbType="Char(1)")]
		public System.Nullable<char> SERI
		{
			get
			{
				return this._SERI;
			}
			set
			{
				if ((this._SERI != value))
				{
					this.OnSERIChanging(value);
					this.SendPropertyChanging();
					this._SERI = value;
					this.SendPropertyChanged("SERI");
					this.OnSERIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SIRANO", DbType="VarChar(10)")]
		public string SIRANO
		{
			get
			{
				return this._SIRANO;
			}
			set
			{
				if ((this._SIRANO != value))
				{
					this.OnSIRANOChanging(value);
					this.SendPropertyChanging();
					this._SIRANO = value;
					this.SendPropertyChanged("SIRANO");
					this.OnSIRANOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TARIH", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> TARIH
		{
			get
			{
				return this._TARIH;
			}
			set
			{
				if ((this._TARIH != value))
				{
					this.OnTARIHChanging(value);
					this.SendPropertyChanging();
					this._TARIH = value;
					this.SendPropertyChanged("TARIH");
					this.OnTARIHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAAT", DbType="Time")]
		public System.Nullable<System.TimeSpan> SAAT
		{
			get
			{
				return this._SAAT;
			}
			set
			{
				if ((this._SAAT != value))
				{
					this.OnSAATChanging(value);
					this.SendPropertyChanging();
					this._SAAT = value;
					this.SendPropertyChanged("SAAT");
					this.OnSAATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERGIDAIRE", DbType="VarChar(40)")]
		public string VERGIDAIRE
		{
			get
			{
				return this._VERGIDAIRE;
			}
			set
			{
				if ((this._VERGIDAIRE != value))
				{
					this.OnVERGIDAIREChanging(value);
					this.SendPropertyChanging();
					this._VERGIDAIRE = value;
					this.SendPropertyChanged("VERGIDAIRE");
					this.OnVERGIDAIREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALICI", DbType="VarChar(30)")]
		public string ALICI
		{
			get
			{
				return this._ALICI;
			}
			set
			{
				if ((this._ALICI != value))
				{
					this.OnALICIChanging(value);
					this.SendPropertyChanging();
					this._ALICI = value;
					this.SendPropertyChanged("ALICI");
					this.OnALICIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TESLIMEDEN", DbType="VarChar(30)")]
		public string TESLIMEDEN
		{
			get
			{
				return this._TESLIMEDEN;
			}
			set
			{
				if ((this._TESLIMEDEN != value))
				{
					this.OnTESLIMEDENChanging(value);
					this.SendPropertyChanging();
					this._TESLIMEDEN = value;
					this.SendPropertyChanged("TESLIMEDEN");
					this.OnTESLIMEDENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TESLIMALAN", DbType="VarChar(30)")]
		public string TESLIMALAN
		{
			get
			{
				return this._TESLIMALAN;
			}
			set
			{
				if ((this._TESLIMALAN != value))
				{
					this.OnTESLIMALANChanging(value);
					this.SendPropertyChanging();
					this._TESLIMALAN = value;
					this.SendPropertyChanged("TESLIMALAN");
					this.OnTESLIMALANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_FATURADETAY")]
	public partial class TBL_FATURADETAY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _FATURAURUNID;
		
		private string _URUNAD;
		
		private System.Nullable<short> _MIKTAR;
		
		private System.Nullable<decimal> _FIYAT;
		
		private System.Nullable<decimal> _TUTAR;
		
		private System.Nullable<int> _FATURAID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnFATURAURUNIDChanging(int value);
    partial void OnFATURAURUNIDChanged();
    partial void OnURUNADChanging(string value);
    partial void OnURUNADChanged();
    partial void OnMIKTARChanging(System.Nullable<short> value);
    partial void OnMIKTARChanged();
    partial void OnFIYATChanging(System.Nullable<decimal> value);
    partial void OnFIYATChanged();
    partial void OnTUTARChanging(System.Nullable<decimal> value);
    partial void OnTUTARChanged();
    partial void OnFATURAIDChanging(System.Nullable<int> value);
    partial void OnFATURAIDChanged();
    #endregion
		
		public TBL_FATURADETAY()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FATURAURUNID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int FATURAURUNID
		{
			get
			{
				return this._FATURAURUNID;
			}
			set
			{
				if ((this._FATURAURUNID != value))
				{
					this.OnFATURAURUNIDChanging(value);
					this.SendPropertyChanging();
					this._FATURAURUNID = value;
					this.SendPropertyChanged("FATURAURUNID");
					this.OnFATURAURUNIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URUNAD", DbType="NVarChar(20)")]
		public string URUNAD
		{
			get
			{
				return this._URUNAD;
			}
			set
			{
				if ((this._URUNAD != value))
				{
					this.OnURUNADChanging(value);
					this.SendPropertyChanging();
					this._URUNAD = value;
					this.SendPropertyChanged("URUNAD");
					this.OnURUNADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MIKTAR", DbType="SmallInt")]
		public System.Nullable<short> MIKTAR
		{
			get
			{
				return this._MIKTAR;
			}
			set
			{
				if ((this._MIKTAR != value))
				{
					this.OnMIKTARChanging(value);
					this.SendPropertyChanging();
					this._MIKTAR = value;
					this.SendPropertyChanged("MIKTAR");
					this.OnMIKTARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIYAT", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> FIYAT
		{
			get
			{
				return this._FIYAT;
			}
			set
			{
				if ((this._FIYAT != value))
				{
					this.OnFIYATChanging(value);
					this.SendPropertyChanging();
					this._FIYAT = value;
					this.SendPropertyChanged("FIYAT");
					this.OnFIYATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TUTAR", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> TUTAR
		{
			get
			{
				return this._TUTAR;
			}
			set
			{
				if ((this._TUTAR != value))
				{
					this.OnTUTARChanging(value);
					this.SendPropertyChanging();
					this._TUTAR = value;
					this.SendPropertyChanged("TUTAR");
					this.OnTUTARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FATURAID", DbType="Int")]
		public System.Nullable<int> FATURAID
		{
			get
			{
				return this._FATURAID;
			}
			set
			{
				if ((this._FATURAID != value))
				{
					this.OnFATURAIDChanging(value);
					this.SendPropertyChanging();
					this._FATURAID = value;
					this.SendPropertyChanged("FATURAID");
					this.OnFATURAIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_ILCELER")]
	public partial class TBL_ILCELER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _ILCE;
		
		private int _SEHIR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnILCEChanging(string value);
    partial void OnILCEChanged();
    partial void OnSEHIRChanging(int value);
    partial void OnSEHIRChanged();
    #endregion
		
		public TBL_ILCELER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ILCE", DbType="NVarChar(255)")]
		public string ILCE
		{
			get
			{
				return this._ILCE;
			}
			set
			{
				if ((this._ILCE != value))
				{
					this.OnILCEChanging(value);
					this.SendPropertyChanging();
					this._ILCE = value;
					this.SendPropertyChanged("ILCE");
					this.OnILCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEHIR", DbType="Int NOT NULL")]
		public int SEHIR
		{
			get
			{
				return this._SEHIR;
			}
			set
			{
				if ((this._SEHIR != value))
				{
					this.OnSEHIRChanging(value);
					this.SendPropertyChanging();
					this._SEHIR = value;
					this.SendPropertyChanged("SEHIR");
					this.OnSEHIRChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_MUSTERILER")]
	public partial class TBL_MUSTERILER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _ID;
		
		private string _AD;
		
		private string _SOYAD;
		
		private string _TELEFON;
		
		private string _TELEFON2;
		
		private string _TC;
		
		private string _MAIL;
		
		private string _IL;
		
		private string _ILCE;
		
		private string _ADRES;
		
		private string _VERGIDAIRE;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(short value);
    partial void OnIDChanged();
    partial void OnADChanging(string value);
    partial void OnADChanged();
    partial void OnSOYADChanging(string value);
    partial void OnSOYADChanged();
    partial void OnTELEFONChanging(string value);
    partial void OnTELEFONChanged();
    partial void OnTELEFON2Changing(string value);
    partial void OnTELEFON2Changed();
    partial void OnTCChanging(string value);
    partial void OnTCChanged();
    partial void OnMAILChanging(string value);
    partial void OnMAILChanged();
    partial void OnILChanging(string value);
    partial void OnILChanged();
    partial void OnILCEChanging(string value);
    partial void OnILCEChanged();
    partial void OnADRESChanging(string value);
    partial void OnADRESChanged();
    partial void OnVERGIDAIREChanging(string value);
    partial void OnVERGIDAIREChanged();
    #endregion
		
		public TBL_MUSTERILER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AD", DbType="VarChar(20)")]
		public string AD
		{
			get
			{
				return this._AD;
			}
			set
			{
				if ((this._AD != value))
				{
					this.OnADChanging(value);
					this.SendPropertyChanging();
					this._AD = value;
					this.SendPropertyChanged("AD");
					this.OnADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOYAD", DbType="VarChar(30)")]
		public string SOYAD
		{
			get
			{
				return this._SOYAD;
			}
			set
			{
				if ((this._SOYAD != value))
				{
					this.OnSOYADChanging(value);
					this.SendPropertyChanging();
					this._SOYAD = value;
					this.SendPropertyChanged("SOYAD");
					this.OnSOYADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFON", DbType="VarChar(15)")]
		public string TELEFON
		{
			get
			{
				return this._TELEFON;
			}
			set
			{
				if ((this._TELEFON != value))
				{
					this.OnTELEFONChanging(value);
					this.SendPropertyChanging();
					this._TELEFON = value;
					this.SendPropertyChanged("TELEFON");
					this.OnTELEFONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFON2", DbType="VarChar(15)")]
		public string TELEFON2
		{
			get
			{
				return this._TELEFON2;
			}
			set
			{
				if ((this._TELEFON2 != value))
				{
					this.OnTELEFON2Changing(value);
					this.SendPropertyChanging();
					this._TELEFON2 = value;
					this.SendPropertyChanged("TELEFON2");
					this.OnTELEFON2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TC", DbType="Char(11)")]
		public string TC
		{
			get
			{
				return this._TC;
			}
			set
			{
				if ((this._TC != value))
				{
					this.OnTCChanging(value);
					this.SendPropertyChanging();
					this._TC = value;
					this.SendPropertyChanged("TC");
					this.OnTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAIL", DbType="VarChar(40)")]
		public string MAIL
		{
			get
			{
				return this._MAIL;
			}
			set
			{
				if ((this._MAIL != value))
				{
					this.OnMAILChanging(value);
					this.SendPropertyChanging();
					this._MAIL = value;
					this.SendPropertyChanged("MAIL");
					this.OnMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IL", DbType="VarChar(13)")]
		public string IL
		{
			get
			{
				return this._IL;
			}
			set
			{
				if ((this._IL != value))
				{
					this.OnILChanging(value);
					this.SendPropertyChanging();
					this._IL = value;
					this.SendPropertyChanged("IL");
					this.OnILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ILCE", DbType="VarChar(20)")]
		public string ILCE
		{
			get
			{
				return this._ILCE;
			}
			set
			{
				if ((this._ILCE != value))
				{
					this.OnILCEChanging(value);
					this.SendPropertyChanging();
					this._ILCE = value;
					this.SendPropertyChanged("ILCE");
					this.OnILCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRES", DbType="VarChar(100)")]
		public string ADRES
		{
			get
			{
				return this._ADRES;
			}
			set
			{
				if ((this._ADRES != value))
				{
					this.OnADRESChanging(value);
					this.SendPropertyChanging();
					this._ADRES = value;
					this.SendPropertyChanged("ADRES");
					this.OnADRESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERGIDAIRE", DbType="VarChar(30)")]
		public string VERGIDAIRE
		{
			get
			{
				return this._VERGIDAIRE;
			}
			set
			{
				if ((this._VERGIDAIRE != value))
				{
					this.OnVERGIDAIREChanging(value);
					this.SendPropertyChanging();
					this._VERGIDAIRE = value;
					this.SendPropertyChanged("VERGIDAIRE");
					this.OnVERGIDAIREChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_NOTLAR")]
	public partial class TBL_NOTLAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _NOTID;
		
		private System.Nullable<System.DateTime> _NOTTARIH;
		
		private System.Nullable<System.TimeSpan> _NOTSAAT;
		
		private string _NOTBASLIK;
		
		private string _NOTDETAY;
		
		private string _NOTOLUSTURAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNOTIDChanging(int value);
    partial void OnNOTIDChanged();
    partial void OnNOTTARIHChanging(System.Nullable<System.DateTime> value);
    partial void OnNOTTARIHChanged();
    partial void OnNOTSAATChanging(System.Nullable<System.TimeSpan> value);
    partial void OnNOTSAATChanged();
    partial void OnNOTBASLIKChanging(string value);
    partial void OnNOTBASLIKChanged();
    partial void OnNOTDETAYChanging(string value);
    partial void OnNOTDETAYChanged();
    partial void OnNOTOLUSTURANChanging(string value);
    partial void OnNOTOLUSTURANChanged();
    #endregion
		
		public TBL_NOTLAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int NOTID
		{
			get
			{
				return this._NOTID;
			}
			set
			{
				if ((this._NOTID != value))
				{
					this.OnNOTIDChanging(value);
					this.SendPropertyChanging();
					this._NOTID = value;
					this.SendPropertyChanged("NOTID");
					this.OnNOTIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTTARIH", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> NOTTARIH
		{
			get
			{
				return this._NOTTARIH;
			}
			set
			{
				if ((this._NOTTARIH != value))
				{
					this.OnNOTTARIHChanging(value);
					this.SendPropertyChanging();
					this._NOTTARIH = value;
					this.SendPropertyChanged("NOTTARIH");
					this.OnNOTTARIHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTSAAT", DbType="Time")]
		public System.Nullable<System.TimeSpan> NOTSAAT
		{
			get
			{
				return this._NOTSAAT;
			}
			set
			{
				if ((this._NOTSAAT != value))
				{
					this.OnNOTSAATChanging(value);
					this.SendPropertyChanging();
					this._NOTSAAT = value;
					this.SendPropertyChanged("NOTSAAT");
					this.OnNOTSAATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTBASLIK", DbType="VarChar(50)")]
		public string NOTBASLIK
		{
			get
			{
				return this._NOTBASLIK;
			}
			set
			{
				if ((this._NOTBASLIK != value))
				{
					this.OnNOTBASLIKChanging(value);
					this.SendPropertyChanging();
					this._NOTBASLIK = value;
					this.SendPropertyChanged("NOTBASLIK");
					this.OnNOTBASLIKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTDETAY", DbType="VarChar(250)")]
		public string NOTDETAY
		{
			get
			{
				return this._NOTDETAY;
			}
			set
			{
				if ((this._NOTDETAY != value))
				{
					this.OnNOTDETAYChanging(value);
					this.SendPropertyChanging();
					this._NOTDETAY = value;
					this.SendPropertyChanged("NOTDETAY");
					this.OnNOTDETAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTOLUSTURAN", DbType="VarChar(20)")]
		public string NOTOLUSTURAN
		{
			get
			{
				return this._NOTOLUSTURAN;
			}
			set
			{
				if ((this._NOTOLUSTURAN != value))
				{
					this.OnNOTOLUSTURANChanging(value);
					this.SendPropertyChanging();
					this._NOTOLUSTURAN = value;
					this.SendPropertyChanged("NOTOLUSTURAN");
					this.OnNOTOLUSTURANChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_STOKLAR")]
	public partial class TBL_STOKLAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _ID;
		
		private string _STOKTUR;
		
		private System.Nullable<short> _STOKADET;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(byte value);
    partial void OnIDChanged();
    partial void OnSTOKTURChanging(string value);
    partial void OnSTOKTURChanged();
    partial void OnSTOKADETChanging(System.Nullable<short> value);
    partial void OnSTOKADETChanged();
    #endregion
		
		public TBL_STOKLAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="TinyInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public byte ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKTUR", DbType="VarChar(20)")]
		public string STOKTUR
		{
			get
			{
				return this._STOKTUR;
			}
			set
			{
				if ((this._STOKTUR != value))
				{
					this.OnSTOKTURChanging(value);
					this.SendPropertyChanging();
					this._STOKTUR = value;
					this.SendPropertyChanged("STOKTUR");
					this.OnSTOKTURChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STOKADET", DbType="SmallInt")]
		public System.Nullable<short> STOKADET
		{
			get
			{
				return this._STOKADET;
			}
			set
			{
				if ((this._STOKADET != value))
				{
					this.OnSTOKADETChanging(value);
					this.SendPropertyChanging();
					this._STOKADET = value;
					this.SendPropertyChanged("STOKADET");
					this.OnSTOKADETChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_URUNLER")]
	public partial class TBL_URUNLER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _URUNAD;
		
		private string _MARKA;
		
		private string _MODEL;
		
		private string _YIL;
		
		private System.Nullable<short> _ADET;
		
		private System.Nullable<decimal> _ALISFIYAT;
		
		private System.Nullable<decimal> _SATISFIYAT;
		
		private string _DETAY;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnURUNADChanging(string value);
    partial void OnURUNADChanged();
    partial void OnMARKAChanging(string value);
    partial void OnMARKAChanged();
    partial void OnMODELChanging(string value);
    partial void OnMODELChanged();
    partial void OnYILChanging(string value);
    partial void OnYILChanged();
    partial void OnADETChanging(System.Nullable<short> value);
    partial void OnADETChanged();
    partial void OnALISFIYATChanging(System.Nullable<decimal> value);
    partial void OnALISFIYATChanged();
    partial void OnSATISFIYATChanging(System.Nullable<decimal> value);
    partial void OnSATISFIYATChanged();
    partial void OnDETAYChanging(string value);
    partial void OnDETAYChanged();
    #endregion
		
		public TBL_URUNLER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URUNAD", DbType="VarChar(20)")]
		public string URUNAD
		{
			get
			{
				return this._URUNAD;
			}
			set
			{
				if ((this._URUNAD != value))
				{
					this.OnURUNADChanging(value);
					this.SendPropertyChanging();
					this._URUNAD = value;
					this.SendPropertyChanged("URUNAD");
					this.OnURUNADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKA", DbType="VarChar(20)")]
		public string MARKA
		{
			get
			{
				return this._MARKA;
			}
			set
			{
				if ((this._MARKA != value))
				{
					this.OnMARKAChanging(value);
					this.SendPropertyChanging();
					this._MARKA = value;
					this.SendPropertyChanged("MARKA");
					this.OnMARKAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MODEL", DbType="VarChar(20)")]
		public string MODEL
		{
			get
			{
				return this._MODEL;
			}
			set
			{
				if ((this._MODEL != value))
				{
					this.OnMODELChanging(value);
					this.SendPropertyChanging();
					this._MODEL = value;
					this.SendPropertyChanged("MODEL");
					this.OnMODELChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YIL", DbType="Char(4)")]
		public string YIL
		{
			get
			{
				return this._YIL;
			}
			set
			{
				if ((this._YIL != value))
				{
					this.OnYILChanging(value);
					this.SendPropertyChanging();
					this._YIL = value;
					this.SendPropertyChanged("YIL");
					this.OnYILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADET", DbType="SmallInt")]
		public System.Nullable<short> ADET
		{
			get
			{
				return this._ADET;
			}
			set
			{
				if ((this._ADET != value))
				{
					this.OnADETChanging(value);
					this.SendPropertyChanging();
					this._ADET = value;
					this.SendPropertyChanged("ADET");
					this.OnADETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ALISFIYAT", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ALISFIYAT
		{
			get
			{
				return this._ALISFIYAT;
			}
			set
			{
				if ((this._ALISFIYAT != value))
				{
					this.OnALISFIYATChanging(value);
					this.SendPropertyChanging();
					this._ALISFIYAT = value;
					this.SendPropertyChanged("ALISFIYAT");
					this.OnALISFIYATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SATISFIYAT", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> SATISFIYAT
		{
			get
			{
				return this._SATISFIYAT;
			}
			set
			{
				if ((this._SATISFIYAT != value))
				{
					this.OnSATISFIYATChanging(value);
					this.SendPropertyChanging();
					this._SATISFIYAT = value;
					this.SendPropertyChanged("SATISFIYAT");
					this.OnSATISFIYATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DETAY", DbType="VarChar(500)")]
		public string DETAY
		{
			get
			{
				return this._DETAY;
			}
			set
			{
				if ((this._DETAY != value))
				{
					this.OnDETAYChanging(value);
					this.SendPropertyChanging();
					this._DETAY = value;
					this.SendPropertyChanged("DETAY");
					this.OnDETAYChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_KULLANICILAR")]
	public partial class TBL_KULLANICILAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Name;
		
		private string _Password;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    #endregion
		
		public TBL_KULLANICILAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(30)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(30)")]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_ILLER")]
	public partial class TBL_ILLER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _SEHIR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSEHIRChanging(string value);
    partial void OnSEHIRChanged();
    #endregion
		
		public TBL_ILLER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEHIR", DbType="NVarChar(255)")]
		public string SEHIR
		{
			get
			{
				return this._SEHIR;
			}
			set
			{
				if ((this._SEHIR != value))
				{
					this.OnSEHIRChanging(value);
					this.SendPropertyChanging();
					this._SEHIR = value;
					this.SendPropertyChanged("SEHIR");
					this.OnSEHIRChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_FIRMALAR")]
	public partial class TBL_FIRMALAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _ID;
		
		private string _AD;
		
		private string _YETKILISTATU;
		
		private string _YETKILIADSOYAD;
		
		private string _TELEFON1;
		
		private string _TELEFON2;
		
		private string _TELEFON3;
		
		private string _MAIL;
		
		private string _FAX;
		
		private string _IL;
		
		private string _ILCE;
		
		private string _VERGIDAIRE;
		
		private string _ADRES;
		
		private string _YETKILITC;
		
		private string _OZELKOD1;
		
		private string _OZELKOD2;
		
		private string _OZELKOD3;
		
		private string _SEKTOR;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(short value);
    partial void OnIDChanged();
    partial void OnADChanging(string value);
    partial void OnADChanged();
    partial void OnYETKILISTATUChanging(string value);
    partial void OnYETKILISTATUChanged();
    partial void OnYETKILIADSOYADChanging(string value);
    partial void OnYETKILIADSOYADChanged();
    partial void OnTELEFON1Changing(string value);
    partial void OnTELEFON1Changed();
    partial void OnTELEFON2Changing(string value);
    partial void OnTELEFON2Changed();
    partial void OnTELEFON3Changing(string value);
    partial void OnTELEFON3Changed();
    partial void OnMAILChanging(string value);
    partial void OnMAILChanged();
    partial void OnFAXChanging(string value);
    partial void OnFAXChanged();
    partial void OnILChanging(string value);
    partial void OnILChanged();
    partial void OnILCEChanging(string value);
    partial void OnILCEChanged();
    partial void OnVERGIDAIREChanging(string value);
    partial void OnVERGIDAIREChanged();
    partial void OnADRESChanging(string value);
    partial void OnADRESChanged();
    partial void OnYETKILITCChanging(string value);
    partial void OnYETKILITCChanged();
    partial void OnOZELKOD1Changing(string value);
    partial void OnOZELKOD1Changed();
    partial void OnOZELKOD2Changing(string value);
    partial void OnOZELKOD2Changed();
    partial void OnOZELKOD3Changing(string value);
    partial void OnOZELKOD3Changed();
    partial void OnSEKTORChanging(string value);
    partial void OnSEKTORChanged();
    #endregion
		
		public TBL_FIRMALAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="SmallInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public short ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AD", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string AD
		{
			get
			{
				return this._AD;
			}
			set
			{
				if ((this._AD != value))
				{
					this.OnADChanging(value);
					this.SendPropertyChanging();
					this._AD = value;
					this.SendPropertyChanged("AD");
					this.OnADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKILISTATU", DbType="VarChar(30)")]
		public string YETKILISTATU
		{
			get
			{
				return this._YETKILISTATU;
			}
			set
			{
				if ((this._YETKILISTATU != value))
				{
					this.OnYETKILISTATUChanging(value);
					this.SendPropertyChanging();
					this._YETKILISTATU = value;
					this.SendPropertyChanged("YETKILISTATU");
					this.OnYETKILISTATUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKILIADSOYAD", DbType="VarChar(30)")]
		public string YETKILIADSOYAD
		{
			get
			{
				return this._YETKILIADSOYAD;
			}
			set
			{
				if ((this._YETKILIADSOYAD != value))
				{
					this.OnYETKILIADSOYADChanging(value);
					this.SendPropertyChanging();
					this._YETKILIADSOYAD = value;
					this.SendPropertyChanged("YETKILIADSOYAD");
					this.OnYETKILIADSOYADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFON1", DbType="VarChar(15)")]
		public string TELEFON1
		{
			get
			{
				return this._TELEFON1;
			}
			set
			{
				if ((this._TELEFON1 != value))
				{
					this.OnTELEFON1Changing(value);
					this.SendPropertyChanging();
					this._TELEFON1 = value;
					this.SendPropertyChanged("TELEFON1");
					this.OnTELEFON1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFON2", DbType="VarChar(15)")]
		public string TELEFON2
		{
			get
			{
				return this._TELEFON2;
			}
			set
			{
				if ((this._TELEFON2 != value))
				{
					this.OnTELEFON2Changing(value);
					this.SendPropertyChanging();
					this._TELEFON2 = value;
					this.SendPropertyChanged("TELEFON2");
					this.OnTELEFON2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFON3", DbType="VarChar(15)")]
		public string TELEFON3
		{
			get
			{
				return this._TELEFON3;
			}
			set
			{
				if ((this._TELEFON3 != value))
				{
					this.OnTELEFON3Changing(value);
					this.SendPropertyChanging();
					this._TELEFON3 = value;
					this.SendPropertyChanged("TELEFON3");
					this.OnTELEFON3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAIL", DbType="VarChar(40)")]
		public string MAIL
		{
			get
			{
				return this._MAIL;
			}
			set
			{
				if ((this._MAIL != value))
				{
					this.OnMAILChanging(value);
					this.SendPropertyChanging();
					this._MAIL = value;
					this.SendPropertyChanged("MAIL");
					this.OnMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAX", DbType="VarChar(15)")]
		public string FAX
		{
			get
			{
				return this._FAX;
			}
			set
			{
				if ((this._FAX != value))
				{
					this.OnFAXChanging(value);
					this.SendPropertyChanging();
					this._FAX = value;
					this.SendPropertyChanged("FAX");
					this.OnFAXChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IL", DbType="VarChar(13)")]
		public string IL
		{
			get
			{
				return this._IL;
			}
			set
			{
				if ((this._IL != value))
				{
					this.OnILChanging(value);
					this.SendPropertyChanging();
					this._IL = value;
					this.SendPropertyChanged("IL");
					this.OnILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ILCE", DbType="VarChar(20)")]
		public string ILCE
		{
			get
			{
				return this._ILCE;
			}
			set
			{
				if ((this._ILCE != value))
				{
					this.OnILCEChanging(value);
					this.SendPropertyChanging();
					this._ILCE = value;
					this.SendPropertyChanged("ILCE");
					this.OnILCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VERGIDAIRE", DbType="VarChar(30)")]
		public string VERGIDAIRE
		{
			get
			{
				return this._VERGIDAIRE;
			}
			set
			{
				if ((this._VERGIDAIRE != value))
				{
					this.OnVERGIDAIREChanging(value);
					this.SendPropertyChanging();
					this._VERGIDAIRE = value;
					this.SendPropertyChanged("VERGIDAIRE");
					this.OnVERGIDAIREChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRES", DbType="VarChar(100)")]
		public string ADRES
		{
			get
			{
				return this._ADRES;
			}
			set
			{
				if ((this._ADRES != value))
				{
					this.OnADRESChanging(value);
					this.SendPropertyChanging();
					this._ADRES = value;
					this.SendPropertyChanged("ADRES");
					this.OnADRESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YETKILITC", DbType="Char(11)")]
		public string YETKILITC
		{
			get
			{
				return this._YETKILITC;
			}
			set
			{
				if ((this._YETKILITC != value))
				{
					this.OnYETKILITCChanging(value);
					this.SendPropertyChanging();
					this._YETKILITC = value;
					this.SendPropertyChanged("YETKILITC");
					this.OnYETKILITCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OZELKOD1", DbType="VarChar(10)")]
		public string OZELKOD1
		{
			get
			{
				return this._OZELKOD1;
			}
			set
			{
				if ((this._OZELKOD1 != value))
				{
					this.OnOZELKOD1Changing(value);
					this.SendPropertyChanging();
					this._OZELKOD1 = value;
					this.SendPropertyChanged("OZELKOD1");
					this.OnOZELKOD1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OZELKOD2", DbType="VarChar(10)")]
		public string OZELKOD2
		{
			get
			{
				return this._OZELKOD2;
			}
			set
			{
				if ((this._OZELKOD2 != value))
				{
					this.OnOZELKOD2Changing(value);
					this.SendPropertyChanging();
					this._OZELKOD2 = value;
					this.SendPropertyChanged("OZELKOD2");
					this.OnOZELKOD2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OZELKOD3", DbType="VarChar(10)")]
		public string OZELKOD3
		{
			get
			{
				return this._OZELKOD3;
			}
			set
			{
				if ((this._OZELKOD3 != value))
				{
					this.OnOZELKOD3Changing(value);
					this.SendPropertyChanging();
					this._OZELKOD3 = value;
					this.SendPropertyChanged("OZELKOD3");
					this.OnOZELKOD3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEKTOR", DbType="VarChar(30)")]
		public string SEKTOR
		{
			get
			{
				return this._SEKTOR;
			}
			set
			{
				if ((this._SEKTOR != value))
				{
					this.OnSEKTORChanging(value);
					this.SendPropertyChanging();
					this._SEKTOR = value;
					this.SendPropertyChanged("SEKTOR");
					this.OnSEKTORChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_OZELKODLAR")]
	public partial class TBL_OZELKODLAR : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _FIRMAKOD1;
		
		private string _FIRMAKOD2;
		
		private string _FIRMAKOD3;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnFIRMAKOD1Changing(string value);
    partial void OnFIRMAKOD1Changed();
    partial void OnFIRMAKOD2Changing(string value);
    partial void OnFIRMAKOD2Changed();
    partial void OnFIRMAKOD3Changing(string value);
    partial void OnFIRMAKOD3Changed();
    #endregion
		
		public TBL_OZELKODLAR()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRMAKOD1", DbType="NVarChar(100)")]
		public string FIRMAKOD1
		{
			get
			{
				return this._FIRMAKOD1;
			}
			set
			{
				if ((this._FIRMAKOD1 != value))
				{
					this.OnFIRMAKOD1Changing(value);
					this.SendPropertyChanging();
					this._FIRMAKOD1 = value;
					this.SendPropertyChanged("FIRMAKOD1");
					this.OnFIRMAKOD1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRMAKOD2", DbType="NVarChar(100)")]
		public string FIRMAKOD2
		{
			get
			{
				return this._FIRMAKOD2;
			}
			set
			{
				if ((this._FIRMAKOD2 != value))
				{
					this.OnFIRMAKOD2Changing(value);
					this.SendPropertyChanging();
					this._FIRMAKOD2 = value;
					this.SendPropertyChanged("FIRMAKOD2");
					this.OnFIRMAKOD2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FIRMAKOD3", DbType="NVarChar(100)")]
		public string FIRMAKOD3
		{
			get
			{
				return this._FIRMAKOD3;
			}
			set
			{
				if ((this._FIRMAKOD3 != value))
				{
					this.OnFIRMAKOD3Changing(value);
					this.SendPropertyChanging();
					this._FIRMAKOD3 = value;
					this.SendPropertyChanged("FIRMAKOD3");
					this.OnFIRMAKOD3Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_PERSONELLER")]
	public partial class TBL_PERSONELLER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _AD;
		
		private string _SOYAD;
		
		private string _TELEFON;
		
		private string _TC;
		
		private string _MAIL;
		
		private string _IL;
		
		private string _ILCE;
		
		private string _ADRES;
		
		private string _GOREV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnADChanging(string value);
    partial void OnADChanged();
    partial void OnSOYADChanging(string value);
    partial void OnSOYADChanged();
    partial void OnTELEFONChanging(string value);
    partial void OnTELEFONChanged();
    partial void OnTCChanging(string value);
    partial void OnTCChanged();
    partial void OnMAILChanging(string value);
    partial void OnMAILChanged();
    partial void OnILChanging(string value);
    partial void OnILChanged();
    partial void OnILCEChanging(string value);
    partial void OnILCEChanged();
    partial void OnADRESChanging(string value);
    partial void OnADRESChanged();
    partial void OnGOREVChanging(string value);
    partial void OnGOREVChanged();
    #endregion
		
		public TBL_PERSONELLER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AD", DbType="VarChar(20)")]
		public string AD
		{
			get
			{
				return this._AD;
			}
			set
			{
				if ((this._AD != value))
				{
					this.OnADChanging(value);
					this.SendPropertyChanging();
					this._AD = value;
					this.SendPropertyChanged("AD");
					this.OnADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOYAD", DbType="VarChar(30)")]
		public string SOYAD
		{
			get
			{
				return this._SOYAD;
			}
			set
			{
				if ((this._SOYAD != value))
				{
					this.OnSOYADChanging(value);
					this.SendPropertyChanging();
					this._SOYAD = value;
					this.SendPropertyChanged("SOYAD");
					this.OnSOYADChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFON", DbType="VarChar(15)")]
		public string TELEFON
		{
			get
			{
				return this._TELEFON;
			}
			set
			{
				if ((this._TELEFON != value))
				{
					this.OnTELEFONChanging(value);
					this.SendPropertyChanging();
					this._TELEFON = value;
					this.SendPropertyChanged("TELEFON");
					this.OnTELEFONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TC", DbType="Char(11)")]
		public string TC
		{
			get
			{
				return this._TC;
			}
			set
			{
				if ((this._TC != value))
				{
					this.OnTCChanging(value);
					this.SendPropertyChanging();
					this._TC = value;
					this.SendPropertyChanged("TC");
					this.OnTCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAIL", DbType="VarChar(40)")]
		public string MAIL
		{
			get
			{
				return this._MAIL;
			}
			set
			{
				if ((this._MAIL != value))
				{
					this.OnMAILChanging(value);
					this.SendPropertyChanging();
					this._MAIL = value;
					this.SendPropertyChanged("MAIL");
					this.OnMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IL", DbType="VarChar(13)")]
		public string IL
		{
			get
			{
				return this._IL;
			}
			set
			{
				if ((this._IL != value))
				{
					this.OnILChanging(value);
					this.SendPropertyChanging();
					this._IL = value;
					this.SendPropertyChanged("IL");
					this.OnILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ILCE", DbType="VarChar(20)")]
		public string ILCE
		{
			get
			{
				return this._ILCE;
			}
			set
			{
				if ((this._ILCE != value))
				{
					this.OnILCEChanging(value);
					this.SendPropertyChanging();
					this._ILCE = value;
					this.SendPropertyChanged("ILCE");
					this.OnILCEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADRES", DbType="VarChar(100)")]
		public string ADRES
		{
			get
			{
				return this._ADRES;
			}
			set
			{
				if ((this._ADRES != value))
				{
					this.OnADRESChanging(value);
					this.SendPropertyChanging();
					this._ADRES = value;
					this.SendPropertyChanged("ADRES");
					this.OnADRESChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GOREV", DbType="VarChar(20)")]
		public string GOREV
		{
			get
			{
				return this._GOREV;
			}
			set
			{
				if ((this._GOREV != value))
				{
					this.OnGOREVChanging(value);
					this.SendPropertyChanging();
					this._GOREV = value;
					this.SendPropertyChanged("GOREV");
					this.OnGOREVChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBL_GIDERLER")]
	public partial class TBL_GIDERLER : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<decimal> _ELEKTRIK;
		
		private System.Nullable<decimal> _SU;
		
		private System.Nullable<decimal> _DOGALGAZ;
		
		private System.Nullable<decimal> _INTERNET;
		
		private System.Nullable<decimal> _MAASLAR;
		
		private System.Nullable<decimal> _EKSTRA;
		
		private string _NOTLAR;
		
		private string _AY;
		
		private string _YIL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnELEKTRIKChanging(System.Nullable<decimal> value);
    partial void OnELEKTRIKChanged();
    partial void OnSUChanging(System.Nullable<decimal> value);
    partial void OnSUChanged();
    partial void OnDOGALGAZChanging(System.Nullable<decimal> value);
    partial void OnDOGALGAZChanged();
    partial void OnINTERNETChanging(System.Nullable<decimal> value);
    partial void OnINTERNETChanged();
    partial void OnMAASLARChanging(System.Nullable<decimal> value);
    partial void OnMAASLARChanged();
    partial void OnEKSTRAChanging(System.Nullable<decimal> value);
    partial void OnEKSTRAChanged();
    partial void OnNOTLARChanging(string value);
    partial void OnNOTLARChanged();
    partial void OnAYChanging(string value);
    partial void OnAYChanged();
    partial void OnYILChanging(string value);
    partial void OnYILChanged();
    #endregion
		
		public TBL_GIDERLER()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ELEKTRIK", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> ELEKTRIK
		{
			get
			{
				return this._ELEKTRIK;
			}
			set
			{
				if ((this._ELEKTRIK != value))
				{
					this.OnELEKTRIKChanging(value);
					this.SendPropertyChanging();
					this._ELEKTRIK = value;
					this.SendPropertyChanged("ELEKTRIK");
					this.OnELEKTRIKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SU", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> SU
		{
			get
			{
				return this._SU;
			}
			set
			{
				if ((this._SU != value))
				{
					this.OnSUChanging(value);
					this.SendPropertyChanging();
					this._SU = value;
					this.SendPropertyChanged("SU");
					this.OnSUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOGALGAZ", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> DOGALGAZ
		{
			get
			{
				return this._DOGALGAZ;
			}
			set
			{
				if ((this._DOGALGAZ != value))
				{
					this.OnDOGALGAZChanging(value);
					this.SendPropertyChanging();
					this._DOGALGAZ = value;
					this.SendPropertyChanged("DOGALGAZ");
					this.OnDOGALGAZChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INTERNET", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> INTERNET
		{
			get
			{
				return this._INTERNET;
			}
			set
			{
				if ((this._INTERNET != value))
				{
					this.OnINTERNETChanging(value);
					this.SendPropertyChanging();
					this._INTERNET = value;
					this.SendPropertyChanged("INTERNET");
					this.OnINTERNETChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAASLAR", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> MAASLAR
		{
			get
			{
				return this._MAASLAR;
			}
			set
			{
				if ((this._MAASLAR != value))
				{
					this.OnMAASLARChanging(value);
					this.SendPropertyChanging();
					this._MAASLAR = value;
					this.SendPropertyChanged("MAASLAR");
					this.OnMAASLARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EKSTRA", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> EKSTRA
		{
			get
			{
				return this._EKSTRA;
			}
			set
			{
				if ((this._EKSTRA != value))
				{
					this.OnEKSTRAChanging(value);
					this.SendPropertyChanging();
					this._EKSTRA = value;
					this.SendPropertyChanged("EKSTRA");
					this.OnEKSTRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOTLAR", DbType="VarChar(500)")]
		public string NOTLAR
		{
			get
			{
				return this._NOTLAR;
			}
			set
			{
				if ((this._NOTLAR != value))
				{
					this.OnNOTLARChanging(value);
					this.SendPropertyChanging();
					this._NOTLAR = value;
					this.SendPropertyChanged("NOTLAR");
					this.OnNOTLARChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AY", DbType="NVarChar(8)")]
		public string AY
		{
			get
			{
				return this._AY;
			}
			set
			{
				if ((this._AY != value))
				{
					this.OnAYChanging(value);
					this.SendPropertyChanging();
					this._AY = value;
					this.SendPropertyChanged("AY");
					this.OnAYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YIL", DbType="Char(4)")]
		public string YIL
		{
			get
			{
				return this._YIL;
			}
			set
			{
				if ((this._YIL != value))
				{
					this.OnYILChanging(value);
					this.SendPropertyChanging();
					this._YIL = value;
					this.SendPropertyChanged("YIL");
					this.OnYILChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
